[tool.poetry]
name = "my-first-llm-py"
version = "0.1.0"
description = "Train a GPT from scratch (learning project)"
authors = ["NeroBlackstone"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
torch = { version = "2.14.1+cu126", source = "pytorch-cu126" }
numpy = "*"
tiktoken = "*"
tqdm = "*"

[[tool.poetry.source]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"
